name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # This will trigger the workflow when changes are pushed to the 'main' branch.

jobs:
  build:
    runs-on: ubuntu-latest  # This specifies the virtual machine image to run the workflow on.

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # This action checks out your code from the repository.

    - name: Set up Python
      uses: actions/setup-python@v2  # This sets up a Python environment.
      with:
        python-version: 3.9  # You can change this to match your project's Python version.

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install the required Python packages.

    - name: Build Docker image
      run: |
        docker build -t todo-devop .  # Build the Docker image with the tag 'flask-todo-app'.

    - name: Log in to Docker Hub
      uses: docker/login-action@v2  # This action logs into Docker Hub using GitHub secrets.
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Set these secrets in your GitHub repository settings.
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image
      run: |
        docker tag flask-todo-app ${{ secrets.DOCKER_USERNAME }}/todo-devop:latest  # Tag the image with your Docker Hub username.
        docker push ${{ secrets.DOCKER_USERNAME }}/todo-devop:latest  # Push the image to Docker Hub.
